// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { id: string, file_name: string, mime: string, size: number, 
/**
 * 画像のときだけ入る。
 */
width: number | null, height: number | null, 
/**
 * サムネイル（`/api/files/{id}/thumb`）があるか。
 */
has_thumb: boolean, };
