// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ボットとして投稿したメッセージの表示名と、投稿したプラグイン。
 */
export type BotInfo = { plugin: string, name: string, };
