// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 通話の参加者（接続）が自分で知らせる状態。サーバーは中身を解釈せずに保存して配る。
 */
export type CallStatus = { 
/**
 * マイクをミュートしている。
 */
muted: boolean, 
/**
 * スピーカーミュート（相手の声を消している）。
 */
deafened: boolean, 
/**
 * WebRTC を使える。`false` ならサーバー経由（リレー）で音声を送る。
 */
rtc: boolean, 
/**
 * 端末の種類（smartphone / tablet / laptop / monitor）。
 */
device: string | null, };
