// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallStatus } from "./CallStatus";

/**
 * 通話にいる接続1つ分。同じ人が2台で入れば2つ。
 */
export type CallMember = { 
/**
 * 参加者が決める接続の ID（シグナリングの宛先に使う）。
 */
peer: string, user_id: string, status: CallStatus, };
