// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * クライアント → サーバー（WebSocket）。
 */
export type ClientEvent = { "type": "message.send", 
/**
 * 仮表示と確定したメッセージを突き合わせるための、クライアントが決める ID。
 */
client_id: string, thread_id: string | null, body: string, 
/**
 * 事前に `POST /api/files` でアップロードした添付ファイルの ID。
 */
attachment_ids: Array<string>, 
/**
 * `true` なら、このメッセージを起点にスレッドを作る。
 */
start_thread: boolean, } | { "type": "message.edit", message_id: string, body: string, } | { "type": "message.delete", message_id: string, } | { "type": "thread.create", root_message_id: string, } | { "type": "reaction.add", message_id: string, emoji: string, } | { "type": "reaction.remove", message_id: string, emoji: string, } | { "type": "ping" };
