// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

/**
 * `POST /api/sessions`
 */
export type CreateSession = { plugin: string, 
/**
 * カードを流すスレッド。`null` ならメインチャット。
 */
thread_id: string | null, state: unknown, card: Card, };
