// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/me/read`
 */
export type MarkRead = { 
/**
 * スレッドの ID。メインチャットなら `null`。
 */
thread_id: string | null, 
/**
 * ここまで読んだメッセージの ID。いまの位置より古ければ何もしない（戻らない）。
 */
message_id: string, };
