// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { BotInfo } from "./BotInfo";
import type { MessageCard } from "./MessageCard";
import type { Reaction } from "./Reaction";
import type { ThreadInfo } from "./ThreadInfo";

export type Message = { id: string, author_id: string, 
/**
 * スレッド内の返信なら、そのスレッド（起点のメッセージ）の ID。メインチャットなら `null`。
 */
thread_id: string | null, 
/**
 * Markdown サブセットの生テキスト。メンションは `<@user_id>`。
 */
body: string, attachments: Array<Attachment>, reactions: Array<Reaction>, created_at: number, edited_at: number | null, 
/**
 * このメッセージがスレッドの起点なら入る。
 */
thread: ThreadInfo | null, 
/**
 * プラグインのセッションのカードなら入る（本文は空）。
 */
card: MessageCard | null, 
/**
 * プラグインがボットとして投稿したメッセージなら入る。`author_id` は投稿を実行した人。
 */
bot: BotInfo | null, };
