// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メッセージに付くカード。タップすると `plugin` の view で `session_id` を開く。
 */
export type MessageCard = { session_id: string, plugin: string, title: string, text: string, };
