// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/plugins/{id}/notify`
 */
export type PluginNotify = { user_ids: Array<string>, body: string, 
/**
 * 指定すると、通知から開いたときにそのカードのある場所を開く。
 */
session_id: string | null, };
