// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * サーバーに配布されたプラグイン。
 */
export type PluginInfo = { 
/**
 * 英小文字・数字・ハイフン（2〜32文字）。
 */
id: string, name: string, version: string, description: string, author: string, min_api_version: number, 
/**
 * manifest の `icon`（Lucide のアイコン名、英小文字・数字・ハイフン）。なければ `null`。
 */
icon: string | null, 
/**
 * `icon.svg` が配布されているか（`/api/plugins/{id}/files/icon.svg`）。
 */
has_icon: boolean, 
/**
 * 配布されているファイル名（`manifest.json` / `main.js` / `styles.css` / `icon.svg`）。
 */
files: Array<string>, 
/**
 * ファイルの中身のハッシュ（16進）。キャッシュの区別と、更新の判定に使う。
 */
hash: string, updated_by: string, updated_at: number, };
