// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/plugins/{id}/messages`
 */
export type PluginPostMessage = { thread_id: string | null, body: string, 
/**
 * 省略するとプラグインの表示名。
 */
name: string | null, };
