// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 既読の位置と未読数（メインチャットかスレッド1つ分）。`GET /api/me/read` と `read.updated` で使う。
 */
export type ReadMarker = { 
/**
 * スレッドの ID。メインチャットなら `null`。
 */
thread_id: string | null, 
/**
 * ここまで読んだ位置。この ID 以下のメッセージは既読（ID の文字列の大小で比べる）。
 * 実在するメッセージの ID とは限らない（一度も既読にしていなければ、アカウントを作った時刻の位置）。
 */
last_read_id: string, 
/**
 * `last_read_id` より新しい、他人のメッセージの数。
 */
unread_count: number, };
