// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotInfo } from "./BotInfo";

/**
 * 返信先のメッセージの要約（引用の表示用）。
 */
export type ReplyPreview = { author_id: string, 
/**
 * 本文の冒頭（改行を空白にして切ったもの）。添付だけなら空。
 */
body: string, has_attachments: boolean, bot: BotInfo | null, };
