// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { Reaction } from "./Reaction";
import type { Thread } from "./Thread";
import type { User } from "./User";

/**
 * サーバー → クライアント（WebSocket）。
 */
export type ServerEvent = { "type": "hello", me: User, users: Array<User>, } | { "type": "message.created", 
/**
 * 送信者本人にだけ入る。
 */
client_id: string | null, message: Message, } | { "type": "message.updated", message: Message, } | { "type": "message.deleted", message_id: string, thread_id: string | null, } | { "type": "thread.updated", thread: Thread, } | { "type": "reaction.updated", message_id: string, reactions: Array<Reaction>, } | { "type": "user.updated", user: User, } | { "type": "notify", title: string, body: string, message_id: string | null, thread_id: string | null, 
/**
 * 「サンプル通知を送信」で送ったもの。アプリを表示中でもシステム通知を出す。
 */
sample: boolean, } | { "type": "error", client_id: string | null, code: string, message: string, } | { "type": "pong" };
