// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallMember } from "./CallMember";
import type { Message } from "./Message";
import type { PluginInfo } from "./PluginInfo";
import type { Reaction } from "./Reaction";
import type { ReadMarker } from "./ReadMarker";
import type { Session } from "./Session";
import type { Thread } from "./Thread";
import type { User } from "./User";

/**
 * サーバー → クライアント（WebSocket）。
 */
export type ServerEvent = { "type": "hello", me: User, users: Array<User>, } | { "type": "message.created", 
/**
 * 送信者本人にだけ入る。
 */
client_id: string | null, message: Message, } | { "type": "message.updated", message: Message, } | { "type": "message.deleted", message_id: string, thread_id: string | null, } | { "type": "thread.updated", thread: Thread, } | { "type": "reaction.updated", message_id: string, reactions: Array<Reaction>, } | { "type": "user.updated", user: User, } | { "type": "notify", title: string, body: string, message_id: string | null, thread_id: string | null, 
/**
 * 「サンプル通知を送信」で送ったもの。アプリを表示中でもシステム通知を出す。
 */
sample: boolean, } | { "type": "plugin.updated", plugin: PluginInfo, } | { "type": "plugin.removed", plugin_id: string, } | { "type": "session.updated", session: Session, } | { "type": "session.event", session_id: string, from: string, name: string, payload: unknown, } | { "type": "plugin.event", plugin: string, from: string, name: string, payload: unknown, } | { "type": "call.state", members: Array<CallMember>, } | { "type": "call.event", 
/**
 * 送った接続の ID（サーバーが付ける）。
 */
peer: string, from: string, name: string, payload: unknown, } | { "type": "call.kicked", by: string, } | { "type": "prefs.updated", prefs: Record<string, unknown>, } | { "type": "read.updated", marker: ReadMarker, } | { "type": "error", client_id: string | null, code: string, message: string, } | { "type": "pong" };
