// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

/**
 * プラグインの「1回分の利用」（ゲームの1局など）。
 */
export type Session = { id: string, plugin: string, 
/**
 * カードのメッセージ。
 */
message_id: string, created_by: string, 
/**
 * プラグインが自由に決める JSON。
 */
state: unknown, 
/**
 * 更新のたびに +1。楽観ロックに使う。
 */
version: number, card: Card, created_at: number, updated_at: number, };
