// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTag } from "./ThreadTag";

/**
 * `PUT /api/threads/{id}/tags`。タグ全体を置き換える（誰でもできる）。
 */
export type SetThreadTags = { tags: Array<ThreadTag>, };
