// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * スレッドのタグ。好きな文字列（絵文字を含む）と、0 か 1 個の Lucide アイコン名。
 */
export type ThreadTag = { label: string, 
/**
 * Lucide のアイコン名（英小文字・数字・ハイフン）。
 */
icon: string | null, };
