// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTag } from "./ThreadTag";

/**
 * `GET /api/thread-tags` の1件。すでに使われているタグと、使っているスレッドの数。
 */
export type ThreadTagUsage = { tag: ThreadTag, count: number, };
