// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * スレッドの情報。スレッドの ID は起点のメッセージの ID と同じ。
 */
export type ThreadInfo = { reply_count: number, last_reply_at: number | null, };
