// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { ThreadInfo } from "./ThreadInfo";

/**
 * スレッド一覧の1件。
 */
export type Thread = { root: Message, info: ThreadInfo, };
