// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTag } from "./ThreadTag";

/**
 * スレッドの情報。スレッドの ID は起点のメッセージの ID と同じ。
 */
export type ThreadInfo = { reply_count: number, last_reply_at: number | null, 
/**
 * スレッドを立てた人。タイトルとアーカイブの設定ができるのはこの人だけ。
 */
created_by: string, 
/**
 * スレッドのタイトル。`null` なら起点のメッセージの冒頭を見出しにする。
 */
title: string | null, 
/**
 * タグ（表示の順）。
 */
tags: Array<ThreadTag>, 
/**
 * アーカイブされているか（一覧でグレーアウトするだけ。返信はできる）。
 */
archived: boolean, };
