// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /api/threads/{id}`。指定した項目だけ変える（スレッドを立てた人だけ）。
 */
export type UpdateThread = { 
/**
 * 新しいタイトル。空文字なら消す（起点の冒頭を見出しにする）。
 */
title: string | null, archived: boolean | null, };
