// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

/**
 * `PUT /api/sessions/{id}`
 */
export type UpdateSession = { 
/**
 * 読み込んだときの version。一致しなければ `409 version_conflict`。
 */
version: number, state: unknown, 
/**
 * 指定するとカードも書き換える。
 */
card: Card | null, };
