// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, 
/**
 * Tailscale のログイン名（例: `alice@github`）。アカウントの識別に使う。
 */
login_name: string, display_name: string, avatar_url: string | null, created_at: number, };
